# Generated by Django 2.1.8 on 2019-04-21 15:19

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=40, unique=True)),
                ('genero', models.CharField(default='Não Identificado', max_length=40)),
                ('Avatar', models.FileField(upload_to=app.models.fnc)),
                ('N_seguidores', models.IntegerField(default=0)),
                ('N_seguindo', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
