# Generated by Django 2.1.8 on 2019-04-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'FEMENINO'), ('D', 'Default')], default='D', max_length=40),
        ),
    ]
